apiVersion: 1
datasources:
  - name: Timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: edr
    user: edr
    secureJsonData:
      password: edrpass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
